# Generated by Django 3.2.7 on 2021-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0007_perrito_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
